[project]
name = "cim-documentation"
version = "0.0.1a"
description = "documentation"
authors = [
    {name = "A. Anderson", email = "19935503+AAndersn@users.noreply.github.com"},
]
readme = "README.md"
requires-python = ">=3.10,<4.0"

dependencies = [
    "cim-graph>=0.5.0a2",
    "pint>=0.24.4",
]

[dependency-groups]
dev = [
    "ipykernel>=6.27.1",
    "nbconvert>=7.16.0",
]

[tool.uv.sources]
cim-graph = {path = "/home/ande188/CIM-Graph", editable = true}
